name: btk_todo
description: "BTK Akademi Todo Uygulaması"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.5.0+1
  envied: ^0.5.4+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^4.2.1
  flutter_svg: ^2.0.10+1
  formz: ^0.7.0
  get_it: ^7.7.0
  go_router: ^14.2.1
  injectable: ^2.4.2
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.1.0
  shared_preferences: ^2.2.3
    
dev_dependencies:
  build_runner: ^2.4.11
  envied_generator: ^0.5.4+1
  flutter_gen_runner: ^5.6.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.2
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/svg/
    - assets/logos/

flutter_gen:
  output: lib/core/gen
  integrations:
    flutter_svg: true